const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();

const Product = require('./models/Product');
const Category = require('./models/Category');

const categories = [
    { name: 'Vegetables & Fruits',   description: 'Fresh vegetables and fruits', sortOrder: 1, icon: 'leaf',           iconType: 'Ionicons',              gradientColors: ['#D5EED8', '#B8E4BC'], accentColor: '#2A7040' },
    { name: 'Dairy, Eggs & Bread',   description: 'Fresh dairy products',        sortOrder: 2, icon: 'egg',            iconType: 'MaterialCommunityIcons',gradientColors: ['#FDE0CC', '#FAC8A8'], accentColor: '#C05020' },
    { name: 'Munchies',              description: 'Snacks and munchies',         sortOrder: 3, icon: 'food-croissant', iconType: 'MaterialCommunityIcons',gradientColors: ['#FFF8E1', '#FFE082'], accentColor: '#F57F17' },
    { name: 'Cold Drinks & Juices',  description: 'Refreshing drinks',           sortOrder: 4, icon: 'beer',           iconType: 'Ionicons',              gradientColors: ['#C8E8F8', '#A8D4F2'], accentColor: '#1A6FA0' },
    { name: 'Noodles & Instant Food',description: 'Quick and easy meals',        sortOrder: 5, icon: 'noodles',        iconType: 'MaterialCommunityIcons',gradientColors: ['#FAD6E8', '#F5B5D2'], accentColor: '#B83060' },
    { name: 'Bakery & Biscuits',     description: 'Baked goods and biscuits',    sortOrder: 6, icon: 'cookie',         iconType: 'MaterialCommunityIcons',gradientColors: ['#E4D5F7', '#D0B8F0'], accentColor: '#6A3AAA' },
    { name: 'Sweet Tooth',           description: 'Chocolates and sweets',       sortOrder: 7, icon: 'candy',          iconType: 'MaterialCommunityIcons',gradientColors: ['#FCE4EC', '#F8BBD0'], accentColor: '#C2185B' },
    { name: 'Atta, Rice & Dal',      description: 'Kitchen staples',             sortOrder: 8, icon: 'grain',          iconType: 'MaterialIcons',         gradientColors: ['#DBF3F7', '#BDE8EF'], accentColor: '#1A8A9A' },
    { name: 'Sauces & Spreads',      description: 'Sauces and condiments',       sortOrder: 9, icon: 'food-variant',   iconType: 'MaterialCommunityIcons',gradientColors: ['#FFCCBC', '#FFAB91'], accentColor: '#D84315' },
    { name: 'Baby Care',             description: 'Baby care products',          sortOrder: 10,icon: 'baby-carriage',  iconType: 'MaterialCommunityIcons',gradientColors: ['#B3E5FC', '#81D4FA'], accentColor: '#0277BD' },
    { name: 'Winter',                description: 'Winter essentials',           sortOrder: 11,icon: 'snow',           iconType: 'Ionicons',              gradientColors: ['#C8E8F8', '#A8D4F2'], accentColor: '#1A6FA0' },
    { name: 'Electronics',           description: 'Electronics & gadgets',       sortOrder: 12,icon: 'hardware-chip',  iconType: 'Ionicons',              gradientColors: ['#E4D5F7', '#D0B8F0'], accentColor: '#6A3AAA' },
    { name: 'Beauty',                description: 'Beauty & skincare',           sortOrder: 13,icon: 'rose',           iconType: 'Ionicons',              gradientColors: ['#FAD6E8', '#F5B5D2'], accentColor: '#B83060' },
    { name: 'Decor',                 description: 'Home decor & furnishing',     sortOrder: 14,icon: 'bulb',           iconType: 'Ionicons',              gradientColors: ['#D5EED8', '#B8E4BC'], accentColor: '#2A7040' },
    { name: 'Kids',                  description: 'Kids toys & essentials',      sortOrder: 15,icon: 'balloon',        iconType: 'Ionicons',              gradientColors: ['#FDE0CC', '#FAC8A8'], accentColor: '#C05020' },
];

const getProducts = (categoryMap) => [
    // ── Vegetables ──────────────────────────────────────────────────────────
    { productKey: 'v1',  name: 'Tomato',       price: 30,  unit: '500g',   stock: 100, badge: 'Fresh',    category: categoryMap['Vegetables & Fruits'], description: 'Sun-ripened tomatoes sourced from local farms. Rich in lycopene and vitamin C, perfect for curries, salads, and chutneys.' },
    { productKey: 'v2',  name: 'Brinjal',      price: 35,  unit: '500g',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Fresh, tender brinjals (eggplant) with a smooth texture. Great for bhartha, sabzi, or grilling.' },
    { productKey: 'v3',  name: 'Cabbage',      price: 28,  unit: '1 pc',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Crisp, leafy cabbage packed with fibre and vitamin K. Ideal for stir-fries, salads, and coleslaw.' },
    { productKey: 'v4',  name: 'Cauliflower',  price: 40,  unit: '1 pc',   stock: 100, badge: 'Popular',  category: categoryMap['Vegetables & Fruits'], description: 'Snow-white cauliflower florets, freshly harvested. Perfect for aloo gobi, soups, or roasting.' },
    { productKey: 'v5',  name: 'Broccoli',     price: 55,  unit: '250g',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Vibrant green broccoli heads rich in iron and antioxidants. Best stir-fried, steamed, or added to pasta.' },
    { productKey: 'v6',  name: 'Onion',        price: 25,  unit: '500g',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Premium quality onions with a sharp, pungent flavour. The backbone of every Indian kitchen.' },
    { productKey: 'v7',  name: 'Potato',       price: 22,  unit: '500g',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Farm-fresh potatoes ideal for sabzi, fries, or mashing. High in potassium and B vitamins.' },
    { productKey: 'v8',  name: 'Garlic',       price: 18,  unit: '100g',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Aromatic whole garlic bulbs bursting with flavour. A natural immunity booster used in countless dishes.' },
    { productKey: 'v9',  name: 'Lemon',        price: 10,  unit: '3 pcs',  stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Juicy, tangy lemons packed with vitamin C. Squeeze over dals, salads, or use in refreshing drinks.' },
    { productKey: 'v10', name: 'Beetroot',     price: 30,  unit: '500g',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Deep red beetroots with natural sweetness. Rich in iron and folate, great for salads and halwa.' },
    { productKey: 'v11', name: 'Carrots',      price: 28,  unit: '500g',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Fresh, crunchy carrots loaded with beta-carotene. Perfect for gajar ka halwa, soups, or raw snacking.' },
    { productKey: 'v12', name: 'Pumpkin',      price: 32,  unit: '500g',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Fresh pumpkin with a mildly sweet flavour. Ideal for curries, soups, and kheer.' },
    { productKey: 'v13', name: 'Sweet Potato', price: 35,  unit: '500g',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Naturally sweet and nutritious sweet potatoes. A healthy alternative packed with dietary fibre.' },
    { productKey: 'v14', name: 'Ginger',       price: 15,  unit: '100g',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Fragrant fresh ginger root with a spicy, warming kick. Essential for chai, marinades, and cooking.' },
    { productKey: 'v15', name: 'Mushrooms',    price: 60,  unit: '200g',   stock: 100, badge: 'Premium',  category: categoryMap['Vegetables & Fruits'], description: 'Premium button mushrooms with an earthy, umami flavour. Great for pasta, pizza, or sautéed on toast.' },

    // ── Fruits ───────────────────────────────────────────────────────────────
    { productKey: 'f1',  name: 'Banana',      price: 45,  unit: '6 pcs',  stock: 100, badge: 'Popular',  category: categoryMap['Vegetables & Fruits'], description: 'Sweet, ripe bananas that are naturally energy-packed. A perfect on-the-go snack for all ages.' },
    { productKey: 'f2',  name: 'Watermelon',  price: 80,  unit: '1 pc',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Refreshing watermelon bursting with hydration and sweetness. Best enjoyed chilled on hot days.' },
    { productKey: 'f3',  name: 'Apple',       price: 90,  unit: '500g',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Crisp, juicy apples with a perfect sweet-tart balance. Rich in fibre and great for snacking.' },
    { productKey: 'f4',  name: 'Orange',      price: 60,  unit: '4 pcs',  stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Fresh, vibrant oranges full of vitamin C and natural citrus flavour. Peel and enjoy or juice them.' },
    { productKey: 'f5',  name: 'Kiwi',        price: 75,  unit: '2 pcs',  stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Tropical kiwis with a tangy-sweet flavour and vivid green flesh. A vitamin C powerhouse.' },
    { productKey: 'f6',  name: 'Strawberry',  price: 99,  unit: '250g',   stock: 100, badge: 'Premium',  category: categoryMap['Vegetables & Fruits'], description: 'Premium plump strawberries with intense sweetness. Perfect for desserts, smoothies, or straight up.' },
    { productKey: 'f7',  name: 'Mango',       price: 85,  unit: '2 pcs',  stock: 100, badge: 'Seasonal', category: categoryMap['Vegetables & Fruits'], description: 'Seasonal Alphonso-variety mangoes with a rich, fragrant sweetness. The king of fruits.' },
    { productKey: 'f8',  name: 'Pineapple',   price: 65,  unit: '1 pc',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Tangy, tropical pineapple with fibrous, juicy flesh. Great for fruit bowls, juices, or grilling.' },
    { productKey: 'f9',  name: 'Papaya',      price: 55,  unit: '1 pc',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Soft, sweet papaya with digestive enzymes (papain). Ideal for breakfast or smoothies.' },
    { productKey: 'f10', name: 'Grapes',      price: 70,  unit: '500g',   stock: 100,                    category: categoryMap['Vegetables & Fruits'], description: 'Sweet, seedless grapes with a burst of natural flavour. Great for snacking or wine pairings.' },

    // ── Dairy, Eggs & Bread ──────────────────────────────────────────────────
    { productKey: 'd1',  name: 'Amul Gold Milk',     price: 31,  unit: '500ml', stock: 100, badge: 'Popular', category: categoryMap['Dairy, Eggs & Bread'], description: 'Amul Gold full-cream milk with a rich, creamy taste. Homogenised and pasteurised for freshness.' },
    { productKey: 'd2',  name: 'Almond Milk',        price: 149, unit: '1L',    stock: 100, badge: 'Premium', category: categoryMap['Dairy, Eggs & Bread'], description: 'Creamy almond milk — dairy-free, low-calorie, and perfect for lattes, smoothies, or cereals.' },
    { productKey: 'd3',  name: 'Amul Fresh Cream',   price: 45,  unit: '200ml', stock: 100,                   category: categoryMap['Dairy, Eggs & Bread'], description: 'Amul fresh cream with a smooth, velvety texture. Perfect for gravies, desserts, and baking.' },
    { productKey: 'd4',  name: 'Dahi',               price: 42,  unit: '400g',  stock: 100, badge: 'Fresh',   category: categoryMap['Dairy, Eggs & Bread'], description: 'Fresh dahi set daily with live probiotic cultures. Creamy, thick, and great with every meal.' },
    { productKey: 'd5',  name: 'Masti Dahi',         price: 55,  unit: '400g',  stock: 100, badge: 'Popular', category: categoryMap['Dairy, Eggs & Bread'], description: 'Masti Dahi — a rich, tangy yoghurt loved for its thick consistency and probiotic benefits.' },
    { productKey: 'd6',  name: 'Amul Lassi',         price: 30,  unit: '200ml', stock: 100,                   category: categoryMap['Dairy, Eggs & Bread'], description: 'Amul chilled lassi, sweet and refreshing. A classic Indian drink best served ice cold.' },
    { productKey: 'd7',  name: 'White Eggs',         price: 89,  unit: '12 pcs',stock: 100,                   category: categoryMap['Dairy, Eggs & Bread'], description: 'Farm-fresh white eggs with a rich yolk. Versatile for every meal, from breakfast to baking.' },
    { productKey: 'd9',  name: 'Bread',              price: 35,  unit: '400g',  stock: 100,                   category: categoryMap['Dairy, Eggs & Bread'], description: 'Soft, fluffy white bread baked fresh daily. Great for sandwiches, toast, or paired with chai.' },
    { productKey: 'd10', name: 'Whole Wheat Bread',  price: 45,  unit: '400g',  stock: 100, badge: 'Healthy', category: categoryMap['Dairy, Eggs & Bread'], description: 'Wholesome whole wheat bread packed with fibre. A healthier, nutty-flavoured alternative.' },

    // ── Munchies ──────────────────────────────────────────────────────────────
    { productKey: 'm1',  name: "Lay's Sweet Spicy",       price: 20,  unit: '26g',  stock: 100, badge: 'Popular', category: categoryMap['Munchies'], description: "Lay's Sweet & Spicy chilli-flavoured crisps — the perfect sweet-heat combo for every snack break." },
    { productKey: 'm2',  name: "Lay's Indian Magic Masala",price: 20,  unit: '26g',  stock: 100,                   category: categoryMap['Munchies'], description: "Lay's Indian Magic Masala — bold, tangy, and packed with desi spice. An all-time Indian favourite." },
    { productKey: 'm3',  name: "Lay's Hot & Sweet Chilli", price: 20,  unit: '26g',  stock: 100,                   category: categoryMap['Munchies'], description: "Lay's Hot & Sweet Chilli — fiery heat meets sweet undertones for an addictive snack experience." },
    { productKey: 'm4',  name: "Lay's Salted",             price: 20,  unit: '26g',  stock: 100,                   category: categoryMap['Munchies'], description: "Classic Lay's Salted — light, crispy, and perfectly seasoned. Simplicity at its snackable best." },
    { productKey: 'm5',  name: 'Pringles Original',        price: 199, unit: '107g', stock: 100, badge: 'Premium', category: categoryMap['Munchies'], description: 'Pringles Original — iconic saddle-shaped crisps with a clean, balanced crunch. Once you pop...' },
    { productKey: 'm6',  name: 'Doritos Nacho Cheese',     price: 50,  unit: '40g',  stock: 100, badge: 'Popular', category: categoryMap['Munchies'], description: 'Doritos Nacho Cheese — bold, cheesy tortilla chips with an intense flavour punch.' },
    { productKey: 'm7',  name: 'Pringles Cream & Onion',   price: 199, unit: '107g', stock: 100,                   category: categoryMap['Munchies'], description: 'Pringles Cream & Onion — smooth, tangy flavour layered on the signature Pringles crunch.' },
    { productKey: 'm8',  name: 'Doritos Spicy Sweet Chilli',price: 50,  unit: '40g',  stock: 100,                   category: categoryMap['Munchies'], description: 'Doritos Spicy Sweet Chilli — the ultimate balance of heat and sweetness in every bite.' },
    { productKey: 'm9',  name: 'Cheetos Cheddar Jalapeño', price: 50,  unit: '40g',  stock: 100, badge: 'Spicy',   category: categoryMap['Munchies'], description: 'Cheetos Cheddar Jalapeño — fiery jalapeño meets sharp cheddar for a bold snacking hit.' },
    { productKey: 'm10', name: 'Takis',                    price: 150, unit: '56g',  stock: 100, badge: 'Spicy',   category: categoryMap['Munchies'], description: 'Takis Fuego — intensely spicy rolled tortilla chips. Not for the faint-hearted.' },
    { productKey: 'm11', name: 'Pringles BBQ',             price: 199, unit: '107g', stock: 100, badge: 'Premium', category: categoryMap['Munchies'], description: 'Pringles BBQ — smoky barbecue flavour packed into every satisfying crisp.' },

    // ── Cold Drinks & Juices ─────────────────────────────────────────────────
    { productKey: 'c1',  name: 'Coca Cola',        price: 45, unit: '750ml', stock: 100, badge: 'Popular', category: categoryMap['Cold Drinks & Juices'], description: "Coca-Cola — the world's most iconic cola. Crisp, refreshing, and perfectly carbonated." },
    { productKey: 'c2',  name: 'Pepsi',            price: 45, unit: '750ml', stock: 100,                   category: categoryMap['Cold Drinks & Juices'], description: "Pepsi — bold, smooth cola flavour that's always refreshing. The choice of a new generation." },
    { productKey: 'c3',  name: 'Sprite',           price: 45, unit: '750ml', stock: 100,                   category: categoryMap['Cold Drinks & Juices'], description: 'Sprite — crisp, clean lemon-lime soda. Refreshing and caffeine-free.' },
    { productKey: 'c4',  name: 'Fanta Orange',     price: 45, unit: '750ml', stock: 100,                   category: categoryMap['Cold Drinks & Juices'], description: 'Fanta Orange — bright, bubbly, and packed with fun orange flavour.' },
    { productKey: 'c5',  name: 'Fanta Berry',      price: 40, unit: '330ml', stock: 100,                   category: categoryMap['Cold Drinks & Juices'], description: 'Fanta Berry — a sparkling berry blast with a vivid, fruity taste.' },
    { productKey: 'c6',  name: 'Fanta Fruit Punch',price: 40, unit: '330ml', stock: 100,                   category: categoryMap['Cold Drinks & Juices'], description: 'Fanta Fruit Punch — a tropical fusion of fruits in every bubbly sip.' },
    { productKey: 'c7',  name: 'Fanta Grape',      price: 40, unit: '330ml', stock: 100,                   category: categoryMap['Cold Drinks & Juices'], description: 'Fanta Grape — sweet, deep grape flavour in a refreshing sparkling drink.' },
    { productKey: 'c8',  name: 'Fanta Green Apple',price: 40, unit: '330ml', stock: 100,                   category: categoryMap['Cold Drinks & Juices'], description: 'Fanta Green Apple — tart, tangy green apple fizziness in every can.' },
    { productKey: 'c9',  name: 'Mango Juice',      price: 30, unit: '200ml', stock: 100, badge: 'Popular', category: categoryMap['Cold Drinks & Juices'], description: 'Real Mango Juice — thick, pulpy mango goodness made from Alphonso mangoes.' },
    { productKey: 'c10', name: 'Moggu Moggu',      price: 60, unit: '320ml', stock: 100, badge: 'New',     category: categoryMap['Cold Drinks & Juices'], description: 'Mogu Mogu — a unique chilled drink with real nata de coco jelly pieces inside. Fun to drink!' },
    { productKey: 'c11', name: 'Orange Juice',     price: 35, unit: '200ml', stock: 100,                   category: categoryMap['Cold Drinks & Juices'], description: 'Fresh Orange Juice — naturally squeezed, vitamin-packed, and full of citrus goodness.' },
    { productKey: 'c12', name: 'Minute Maid Pulpy',price: 25, unit: '400ml', stock: 100, badge: 'Popular', category: categoryMap['Cold Drinks & Juices'], description: 'Minute Maid Pulpy Orange — juicy with real orange pulp for an authentic fruit experience.' },
    { productKey: 'c13', name: 'Tropicana',        price: 99, unit: '1L',    stock: 100, badge: 'Premium', category: categoryMap['Cold Drinks & Juices'], description: 'Tropicana 100% — pure squeezed orange juice with no added sugar or preservatives.' },
    { productKey: 'c14', name: 'Cherry Juice',     price: 80, unit: '500ml', stock: 100,                   category: categoryMap['Cold Drinks & Juices'], description: 'Cherry Juice — deep, rich cherry flavour packed with antioxidants.' },
    { productKey: 'c15', name: 'Blueberry Drink',  price: 80, unit: '330ml', stock: 100, badge: 'New',     category: categoryMap['Cold Drinks & Juices'], description: 'Blueberry Drink — a vibrant, antioxidant-rich blueberry beverage.' },

    // ── Noodles & Instant Food ───────────────────────────────────────────────
    { productKey: 'n1', name: 'Buldak Black',      price: 180, unit: '1 pc', stock: 100, badge: 'Spicy',   category: categoryMap['Noodles & Instant Food'], description: 'Buldak Black — Korean carbonara fire noodles with an insanely rich and spicy sauce. Challenge accepted?' },
    { productKey: 'n2', name: 'Buldak Pink',       price: 180, unit: '1 pc', stock: 100, badge: 'Popular', category: categoryMap['Noodles & Instant Food'], description: 'Buldak Pink — mildly spicy rose flavour ramen from Korea. Creamy, tangy, and addictive.' },
    { productKey: 'n3', name: 'Buldak Yellow',     price: 180, unit: '1 pc', stock: 100,                   category: categoryMap['Noodles & Instant Food'], description: 'Buldak Yellow — curry-flavoured Korean fire noodles with a warming, aromatic kick.' },
    { productKey: 'n4', name: 'Maggi Masala Cup',  price: 30,  unit: '70g',  stock: 100, badge: 'Popular', category: categoryMap['Noodles & Instant Food'], description: 'Maggi Masala Cup — the beloved 2-minute noodle cup. Just add hot water and slurp away.' },
    { productKey: 'n5', name: 'Maggi Curry Flavour',price: 14, unit: '70g',  stock: 100,                   category: categoryMap['Noodles & Instant Food'], description: 'Maggi Curry Flavour — classic Maggi noodles with a fragrant curry twist.' },
    { productKey: 'n6', name: 'MTR Poha',          price: 45,  unit: '80g',  stock: 100,                   category: categoryMap['Noodles & Instant Food'], description: 'MTR Poha — ready-made poha mix for a quick, authentic South Indian breakfast in minutes.' },
    { productKey: 'n7', name: 'MTR Upma',          price: 45,  unit: '80g',  stock: 100,                   category: categoryMap['Noodles & Instant Food'], description: 'MTR Upma — traditional South Indian upma mix. Fluffy, savoury, and ready in 5 minutes.' },
    { productKey: 'n8', name: 'Yippee Noodles',    price: 14,  unit: '70g',  stock: 100, badge: 'Popular', category: categoryMap['Noodles & Instant Food'], description: "Yippee Noodles — Sun Feast's popular wavy noodles in a tangy, spicy masala broth." },

    // ── Bakery & Biscuits ────────────────────────────────────────────────────
    { productKey: 'b1',  name: 'Chocolate Cookie',  price: 30, unit: '75g',  stock: 100, badge: 'Popular', category: categoryMap['Bakery & Biscuits'], description: 'Chocolate Chip Cookie — crispy, golden cookies loaded with milk chocolate chips.' },
    { productKey: 'b2',  name: 'Desire Butter',     price: 20, unit: '100g', stock: 100,                   category: categoryMap['Bakery & Biscuits'], description: 'Desire Butter Cookies — light, melt-in-your-mouth butter biscuits with a delicate sweetness.' },
    { productKey: 'b3',  name: 'Moms Magic',        price: 25, unit: '100g', stock: 100,                   category: categoryMap['Bakery & Biscuits'], description: "Mom's Magic — crisp and lightly sweetened biscuits perfect for dunking in chai." },
    { productKey: 'b4',  name: 'Fifty Fifty',       price: 20, unit: '66g',  stock: 100, badge: 'Popular', category: categoryMap['Bakery & Biscuits'], description: "Fifty Fifty — Britannia's beloved sweet and salted biscuit combo. Addictively balanced." },
    { productKey: 'b5',  name: 'Marie Gold',        price: 25, unit: '250g', stock: 100,                   category: categoryMap['Bakery & Biscuits'], description: 'Marie Gold — classic thin biscuits with a subtle sweetness. A timeless chai companion.' },
    { productKey: 'b6',  name: 'Jim Jam',           price: 20, unit: '100g', stock: 100,                   category: categoryMap['Bakery & Biscuits'], description: 'Jim Jam — cream-filled biscuits with a fruity, jammy centre. A childhood favourite.' },
    { productKey: 'b7',  name: 'Little Hearts',     price: 20, unit: '75g',  stock: 100, badge: 'Popular', category: categoryMap['Bakery & Biscuits'], description: 'Little Hearts — heart-shaped puff pastry biscuits with a delicate, buttery crunch.' },
    { productKey: 'b8',  name: 'Milk Bikis',        price: 10, unit: '56g',  stock: 100,                   category: categoryMap['Bakery & Biscuits'], description: 'Milk Bikis — nutritious milk biscuits enriched with calcium. A kids snack staple.' },
    { productKey: 'b9',  name: 'Nutri Choice',      price: 30, unit: '100g', stock: 100, badge: 'Healthy', category: categoryMap['Bakery & Biscuits'], description: 'NutriChoice — digestive biscuits baked with whole grains and zero trans-fat. Guilt-free snacking.' },
    { productKey: 'b10', name: 'Bourbon',           price: 20, unit: '100g', stock: 100, badge: 'Popular', category: categoryMap['Bakery & Biscuits'], description: 'Bourbon — two dark cocoa biscuits sandwiching a rich chocolate cream. A classic treat.' },
    { productKey: 'b11', name: 'Happy Happy Oreo',  price: 20, unit: '120g', stock: 100,                   category: categoryMap['Bakery & Biscuits'], description: 'Happy Happy Oreo — double-stuffed cream cookies in a fun pack. More cream, more fun.' },
    { productKey: 'b12', name: 'Hide & Seek',       price: 30, unit: '100g', stock: 100,                   category: categoryMap['Bakery & Biscuits'], description: 'Hide & Seek — chocolate chip cookies with a satisfying crunch from Parle.' },
    { productKey: 'b13', name: 'Unibic Chocolate',  price: 40, unit: '75g',  stock: 100, badge: 'Premium', category: categoryMap['Bakery & Biscuits'], description: 'Unibic Chocolate Chip — premium choco-chip cookies baked with real chocolate.' },
    { productKey: 'b14', name: 'Unibic Fruit & Nut',price: 40, unit: '75g',  stock: 100, badge: 'Premium', category: categoryMap['Bakery & Biscuits'], description: 'Unibic Fruit & Nut — premium cookies loaded with dry fruits, nuts, and rich flavour.' },
    { productKey: 'b15', name: 'Oreo Original',     price: 20, unit: '120g', stock: 100, badge: 'Popular', category: categoryMap['Bakery & Biscuits'], description: 'Oreo Original — the iconic chocolate sandwich cookie with sweet cream filling. Twist, lick, dunk.' },
    { productKey: 'b16', name: 'Oreo Strawberry',   price: 20, unit: '120g', stock: 100,                   category: categoryMap['Bakery & Biscuits'], description: "Oreo Strawberry — Oreo's classic format with a sweet strawberry cream twist." },

    // ── Sweet Tooth ──────────────────────────────────────────────────────────
    { productKey: 's1',  name: 'Cornetto Choco',      price: 50,  unit: '1 pc',   stock: 100, badge: 'Popular', category: categoryMap['Sweet Tooth'], description: 'Cornetto Choco — classic waffle cone filled with creamy chocolate ice cream and a chocolate tip.' },
    { productKey: 's2',  name: 'Cornetto Blue',       price: 50,  unit: '1 pc',   stock: 100,                   category: categoryMap['Sweet Tooth'], description: 'Cornetto Blue — a blueberry-flavoured cone ice cream with a fruity, creamy swirl.' },
    { productKey: 's3',  name: 'Magnum',              price: 90,  unit: '1 pc',   stock: 100, badge: 'Premium', category: categoryMap['Sweet Tooth'], description: 'Magnum — premium chocolate-coated vanilla ice cream bar. Pure indulgence on a stick.' },
    { productKey: 's4',  name: 'Ferrero Rocher',      price: 199, unit: '16 pcs', stock: 100, badge: 'Premium', category: categoryMap['Sweet Tooth'], description: 'Ferrero Rocher — luxurious hazelnut chocolates in a golden wrapper. The gift of elegance.' },
    { productKey: 's5',  name: 'KitKat Biscoff',      price: 60,  unit: '1 pc',   stock: 100,                   category: categoryMap['Sweet Tooth'], description: 'KitKat Biscoff — KitKat with a Lotus Biscoff caramel wafer twist. Break. Enjoy.' },
    { productKey: 's6',  name: 'KitKat Cookie Crumble',price: 60, unit: '1 pc',   stock: 100,                   category: categoryMap['Sweet Tooth'], description: 'KitKat Cookie Crumble — chocolate-coated wafer bar with a cookie crumble crunch.' },
    { productKey: 's7',  name: 'Oreo Bites',          price: 50,  unit: '75g',    stock: 100, badge: 'New',     category: categoryMap['Sweet Tooth'], description: 'Oreo Bites — bite-sized Oreo crunch balls coated in creamy chocolate.' },
    { productKey: 's8',  name: 'Snickers Minis',      price: 99,  unit: '162g',   stock: 100, badge: 'Popular', category: categoryMap['Sweet Tooth'], description: 'Snickers Minis — miniature peanut, caramel, and nougat chocolate bars. Share the joy.' },
    { productKey: 's9',  name: 'Toblerone',           price: 180, unit: '100g',   stock: 100, badge: 'Premium', category: categoryMap['Sweet Tooth'], description: 'Toblerone — the iconic Swiss milk chocolate bar with honey-almond nougat in every triangular peak.' },
    { productKey: 's10', name: 'Twix',                price: 60,  unit: '50g',    stock: 100,                   category: categoryMap['Sweet Tooth'], description: 'Twix — caramel and biscuit dipped in milk chocolate. Perfect for sharing (if you want to).' },
    { productKey: 's11', name: 'Kinder Joy',          price: 40,  unit: '1 pc',   stock: 100, badge: 'Popular', category: categoryMap['Sweet Tooth'], description: 'Kinder Joy — a surprise toy inside a creamy chocolate egg. Kids absolutely love it.' },
    { productKey: 's12', name: 'Mars Minis',          price: 99,  unit: '162g',   stock: 100,                   category: categoryMap['Sweet Tooth'], description: 'Mars Minis — miniature chocolate bars with caramel and nougat. Irresistible in small doses.' },
    { productKey: 's13', name: 'Bounty',              price: 60,  unit: '57g',    stock: 100,                   category: categoryMap['Sweet Tooth'], description: 'Bounty — tender coconut and milk chocolate combo. A tropical treat in every bite.' },
    { productKey: 's14', name: 'Rafaello',            price: 299, unit: '150g',   stock: 100, badge: 'Premium', category: categoryMap['Sweet Tooth'], description: 'Raffaello — delicate coconut and almond pralines wrapped in white chocolate. Pure luxury.' },

    // ── Atta, Rice & Dal ─────────────────────────────────────────────────────
    { productKey: 'ar1', name: 'Aashirvaad Atta',    price: 280, unit: '5kg',  stock: 100, badge: 'Popular', category: categoryMap['Atta, Rice & Dal'], description: 'Aashirvaad Atta — freshly milled whole wheat flour for soft, nutritious rotis every day.' },
    { productKey: 'ar2', name: 'Bhog Atta',          price: 240, unit: '5kg',  stock: 100,                   category: categoryMap['Atta, Rice & Dal'], description: 'Bhog Atta — finely milled chakki atta with no added preservatives. Classic rotis, every time.' },
    { productKey: 'ar3', name: 'Daawat Brown Rice',  price: 180, unit: '1kg',  stock: 100, badge: 'Healthy', category: categoryMap['Atta, Rice & Dal'], description: 'Daawat Brown Rice — nutty, fibre-rich brown rice with a low glycaemic index for healthier meals.' },
    { productKey: 'ar4', name: 'India Gate Basmati', price: 320, unit: '1kg',  stock: 100, badge: 'Premium', category: categoryMap['Atta, Rice & Dal'], description: 'India Gate Basmati — extra-long grain premium basmati rice with a fragrant, aromatic quality.' },
    { productKey: 'ar5', name: 'Masoor Dal',         price: 120, unit: '500g', stock: 100,                   category: categoryMap['Atta, Rice & Dal'], description: 'Masoor Dal — red lentils that cook quickly and are rich in protein and iron.' },
    { productKey: 'ar6', name: 'Moong Dal',          price: 130, unit: '500g', stock: 100, badge: 'Popular', category: categoryMap['Atta, Rice & Dal'], description: "Moong Dal — split green gram that's light on the stomach and high in nutrients." },
    { productKey: 'ar7', name: 'Toor Dal',           price: 110, unit: '500g', stock: 100,                   category: categoryMap['Atta, Rice & Dal'], description: 'Toor Dal — yellow pigeon peas, the base of classic dal tadka. A pantry essential.' },
    { productKey: 'ar8', name: 'Urad Dal',           price: 115, unit: '500g', stock: 100,                   category: categoryMap['Atta, Rice & Dal'], description: 'Urad Dal — black gram dal used in dal makhani and idli/dosa batter. Protein-packed.' },
    { productKey: 'ar9', name: 'Saffola Masala Oats',price: 75,  unit: '39g',  stock: 100, badge: 'Healthy', category: categoryMap['Atta, Rice & Dal'], description: 'Saffola Masala Oats — a savoury, flavourful oats mix ready in 3 minutes. Healthy never tasted this good.' },

    // ── Sauces & Spreads ─────────────────────────────────────────────────────
    { productKey: 'sc1',  name: 'Heinz BBQ Sauce',      price: 299, unit: '875ml', stock: 100, badge: 'Popular', category: categoryMap['Sauces & Spreads'], description: 'Heinz BBQ Sauce — bold, smoky barbecue sauce perfect for grilling, dipping, and marinades.' },
    { productKey: 'sc2',  name: 'Hershey Strawberry',   price: 120, unit: '200ml', stock: 100,                   category: categoryMap['Sauces & Spreads'], description: "Hershey's Strawberry Syrup — sweet strawberry sauce for ice cream, pancakes, or milkshakes." },
    { productKey: 'sc3',  name: 'Hershey Caramel',      price: 120, unit: '200ml', stock: 100,                   category: categoryMap['Sauces & Spreads'], description: "Hershey's Caramel Syrup — rich, golden caramel drizzle for desserts and beverages." },
    { productKey: 'sc4',  name: 'Hershey Chocolate',    price: 120, unit: '200ml', stock: 100, badge: 'Popular', category: categoryMap['Sauces & Spreads'], description: "Hershey's Chocolate Syrup — the classic chocolate drizzle for sundaes, brownies, and hot cocoa." },
    { productKey: 'sc5',  name: 'Heinz Hot Chilli Sauce',price: 199, unit: '300ml', stock: 100, badge: 'Spicy',   category: categoryMap['Sauces & Spreads'], description: 'Heinz Hot Chilli Sauce — fiery, tangy chilli sauce to spice up any dish or dip.' },
    { productKey: 'sc6',  name: 'Heinz Mayonnaise',     price: 179, unit: '400ml', stock: 100,                   category: categoryMap['Sauces & Spreads'], description: 'Heinz Mayonnaise — creamy, thick mayo made with real eggs. Perfect for sandwiches and dips.' },
    { productKey: 'sc7',  name: "Rao's Pasta Sauce",    price: 599, unit: '680g',  stock: 100, badge: 'Premium', category: categoryMap['Sauces & Spreads'], description: "Rao's Arrabbiata — authentic Italian pasta sauce with a spicy tomato base. Restaurant quality at home." },
    { productKey: 'sc8',  name: 'Heinz Tandoori Mayo',  price: 179, unit: '400ml', stock: 100,                   category: categoryMap['Sauces & Spreads'], description: 'Heinz Tandoori Mayo — a spiced, smoky tandoori-flavoured mayo for wraps and sandwiches.' },
    { productKey: 'sc9',  name: "Rao's Tomato Basil",   price: 599, unit: '680g',  stock: 100, badge: 'Premium', category: categoryMap['Sauces & Spreads'], description: "Rao's Tomato Basil — slow-simmered marinara with fresh basil and premium Italian tomatoes." },
    { productKey: 'sc10', name: 'Heinz Tomato Ketchup', price: 149, unit: '450ml', stock: 100, badge: 'Popular', category: categoryMap['Sauces & Spreads'], description: "Heinz Tomato Ketchup — the world-famous ketchup. Perfect for everything from fries to momos." },
    { productKey: 'sc11', name: 'Heinz Yellow Mustard', price: 199, unit: '395ml', stock: 100,                   category: categoryMap['Sauces & Spreads'], description: 'Heinz Yellow Mustard — classic American-style yellow mustard. Sharp, tangy, and bold.' },

    // ── Baby Care ────────────────────────────────────────────────────────────
    { productKey: 'bc1', name: 'Baby Rub',            price: 199, unit: '50g',   stock: 100, badge: 'Popular', category: categoryMap['Baby Care'], description: 'Baby Rub — gentle vapour rub specially formulated for babies to relieve congestion and cold symptoms.' },
    { productKey: 'bc2', name: 'Johnson Aloe Powder', price: 149, unit: '200g',  stock: 100,                   category: categoryMap['Baby Care'], description: "Johnson's Aloe Powder — soft talc-free powder with aloe vera for baby's delicate skin." },
    { productKey: 'bc3', name: 'Johnson Baby Cream',  price: 129, unit: '200g',  stock: 100, badge: 'Popular', category: categoryMap['Baby Care'], description: "Johnson's Baby Cream — mild, hypoallergenic moisturising cream that keeps baby skin soft and healthy." },
    { productKey: 'bc4', name: 'Johnson Baby Oil',    price: 179, unit: '200ml', stock: 100,                   category: categoryMap['Baby Care'], description: "Johnson's Baby Oil — pure, gentle mineral oil for baby massage. Nourishes and softens skin." },
    { productKey: 'bc5', name: 'Johnson Baby Powder', price: 149, unit: '200g',  stock: 100,                   category: categoryMap['Baby Care'], description: "Johnson's Baby Powder — classic, clinically proven gentle powder for everyday freshness." },
    { productKey: 'bc6', name: 'Johnson Baby Wipes',  price: 199, unit: '80 pcs',stock: 100, badge: 'Popular', category: categoryMap['Baby Care'], description: "Johnson's Baby Wipes — soft, alcohol-free wipes with aloe vera for gentle everyday cleaning." },
    { productKey: 'bc7', name: 'Pampers Diapers',     price: 699, unit: '40 pcs',stock: 100, badge: 'Premium', category: categoryMap['Baby Care'], description: 'Pampers Diapers — ultra-soft, highly absorbent diapers with a snug fit for leak-free comfort.' },
    { productKey: 'bc8', name: 'Pampers Baby Wipes',  price: 249, unit: '72 pcs',stock: 100,                   category: categoryMap['Baby Care'], description: 'Pampers Baby Wipes — triple clean formula wipes that are gentle on skin and tough on mess.' },

    // ── Winter ──────────────────────────────────────────────────────────────
    { productKey: 'wi1',  name: 'Wool Sweater',          price: 899,  unit: '1 pc',  stock: 50,  badge: 'Popular', category: categoryMap['Winter'], imageUrl: 'https://picsum.photos/seed/wool-sweater/400/400', description: 'Classic wool sweater with a ribbed knit pattern. Warm, breathable, and perfect for chilly days.' },
    { productKey: 'wi2',  name: 'Puffer Jacket',         price: 1999, unit: '1 pc',  stock: 30,  badge: 'Premium', category: categoryMap['Winter'], imageUrl: 'https://picsum.photos/seed/puffer-jacket/400/400', description: 'Lightweight puffer jacket with synthetic down fill. Water-resistant and ultra-warm.' },
    { productKey: 'wi3',  name: 'Fleece Blanket',        price: 599,  unit: '1 pc',  stock: 80,  badge: 'Popular', category: categoryMap['Winter'], imageUrl: 'https://picsum.photos/seed/fleece-blanket/400/400', description: 'Soft fleece blanket (60x80 inches). Cosy for movie nights, naps, or layering on beds.' },
    { productKey: 'wi4',  name: 'Room Heater',           price: 2499, unit: '1 pc',  stock: 20,  badge: 'Best Seller', category: categoryMap['Winter'], imageUrl: 'https://picsum.photos/seed/room-heater/400/400', description: '2000W fan-forced room heater with adjustable thermostat and tip-over safety cut-off.' },
    { productKey: 'wi5',  name: 'Thermal Socks (3 Pack)',price: 299,  unit: '3 pcs', stock: 100,                   category: categoryMap['Winter'], imageUrl: 'https://picsum.photos/seed/thermal-socks/400/400', description: 'Thick thermal socks with cushioned soles. Keeps feet warm in extreme cold.' },
    { productKey: 'wi6',  name: 'Beanie Cap',            price: 199,  unit: '1 pc',  stock: 100,                   category: categoryMap['Winter'], imageUrl: 'https://picsum.photos/seed/beanie-cap/400/400', description: 'Knitted acrylic beanie cap with a snug fit. Lightweight yet warm for outdoor wear.' },
    { productKey: 'wi7',  name: 'Woollen Gloves',        price: 249,  unit: '1 pair',stock: 100, badge: 'New',     category: categoryMap['Winter'], imageUrl: 'https://picsum.photos/seed/wool-gloves/400/400', description: 'Touch-screen compatible woollen gloves. Stay connected without freezing your fingers.' },
    { productKey: 'wi8',  name: 'Hot Water Bottle',      price: 349,  unit: '1 pc',  stock: 60,                    category: categoryMap['Winter'], imageUrl: 'https://picsum.photos/seed/hot-water-bottle/400/400', description: 'Rubber hot water bottle with a soft cover. Soothing warmth for cold nights and muscle pain.' },
    { productKey: 'wi9',  name: 'Electric Blanket',      price: 1799, unit: '1 pc',  stock: 25,  badge: 'Premium', category: categoryMap['Winter'], imageUrl: 'https://picsum.photos/seed/electric-blanket/400/400', description: 'Electric heated blanket with 3 heat settings and auto shut-off. Stay toasty all night.' },
    { productKey: 'wi10', name: 'Windbreaker Jacket',    price: 1299, unit: '1 pc',  stock: 40,                    category: categoryMap['Winter'], imageUrl: 'https://picsum.photos/seed/windbreaker/400/400', description: 'Lightweight windbreaker with a zippered front and hood. Blocks cold wind effectively.' },
    { productKey: 'wi11', name: 'Thermal Innerwear Set', price: 499,  unit: '1 set', stock: 70,  badge: 'Popular', category: categoryMap['Winter'], imageUrl: 'https://picsum.photos/seed/thermal-innerwear/400/400', description: 'Full-sleeve thermal top and bottom set. Traps body heat for all-day warmth.' },
    { productKey: 'wi12', name: 'Wool Muffler',          price: 349,  unit: '1 pc',  stock: 90,                    category: categoryMap['Winter'], imageUrl: 'https://picsum.photos/seed/wool-muffler/400/400', description: 'Long woollen muffler/scarf in a classic check pattern. Wraps snugly around the neck.' },

    // ── Electronics ─────────────────────────────────────────────────────────
    { productKey: 'el1',  name: 'boAt Rockerz 450',       price: 1499, unit: '1 pc',  stock: 40,  badge: 'Popular',     category: categoryMap['Electronics'], imageUrl: 'https://picsum.photos/seed/headphones-black/400/400', description: 'boAt Rockerz 450 wireless headphones with 40mm drivers, 15-hour battery, and padded ear cushions.' },
    { productKey: 'el2',  name: 'boAt Airdopes 141',      price: 999,  unit: '1 pc',  stock: 60,  badge: 'Best Seller', category: categoryMap['Electronics'], imageUrl: 'https://picsum.photos/seed/wireless-earbuds/400/400', description: 'boAt Airdopes 141 TWS earbuds with Bluetooth 5.1, 42-hour playback, and IPX4 water resistance.' },
    { productKey: 'el3',  name: 'JBL Flip 6 Speaker',     price: 9999, unit: '1 pc',  stock: 15,  badge: 'Premium',     category: categoryMap['Electronics'], imageUrl: 'https://picsum.photos/seed/bluetooth-speaker/400/400', description: 'JBL Flip 6 portable Bluetooth speaker. IP67 waterproof, 12-hour battery, and powerful bass.' },
    { productKey: 'el4',  name: 'Anker 20W Charger',      price: 999,  unit: '1 pc',  stock: 80,  badge: 'Popular',     category: categoryMap['Electronics'], imageUrl: 'https://picsum.photos/seed/phone-charger/400/400', description: 'Anker 20W USB-C fast charger with PowerIQ 3.0. Charges iPhone and Android at top speed.' },
    { productKey: 'el5',  name: 'USB-C Cable (1m)',        price: 299,  unit: '1 pc',  stock: 150,                       category: categoryMap['Electronics'], imageUrl: 'https://picsum.photos/seed/usb-cable/400/400', description: 'Braided USB-C to USB-C cable (1 metre). 60W fast charging and data transfer support.' },
    { productKey: 'el6',  name: 'Ambrane 10000mAh Bank',  price: 799,  unit: '1 pc',  stock: 50,  badge: 'Popular',     category: categoryMap['Electronics'], imageUrl: 'https://picsum.photos/seed/power-bank/400/400', description: 'Ambrane 10000mAh power bank with dual USB output and Type-C input. Slim, portable design.' },
    { productKey: 'el7',  name: 'Fire-Boltt Smartwatch',  price: 1499, unit: '1 pc',  stock: 35,  badge: 'New',         category: categoryMap['Electronics'], imageUrl: 'https://picsum.photos/seed/smartwatch/400/400', description: 'Fire-Boltt Phoenix smartwatch with 1.3" display, SpO2, heart rate, and 7-day battery life.' },
    { productKey: 'el8',  name: 'Portronics Mouse',       price: 499,  unit: '1 pc',  stock: 70,                        category: categoryMap['Electronics'], imageUrl: 'https://picsum.photos/seed/wireless-mouse/400/400', description: 'Portronics wireless optical mouse with 2.4GHz nano receiver. Silent clicks, ergonomic shape.' },
    { productKey: 'el9',  name: 'LED Desk Lamp',          price: 899,  unit: '1 pc',  stock: 45,                        category: categoryMap['Electronics'], imageUrl: 'https://picsum.photos/seed/desk-lamp/400/400', description: 'USB-powered LED desk lamp with 3 brightness levels and flexible gooseneck. Eye-care design.' },
    { productKey: 'el10', name: 'Noise Earbuds',          price: 1299, unit: '1 pc',  stock: 55,  badge: 'Popular',     category: categoryMap['Electronics'], imageUrl: 'https://picsum.photos/seed/noise-earbuds/400/400', description: 'Noise Buds VS104 TWS earbuds with ANC, 45-hour battery, and low-latency gaming mode.' },
    { productKey: 'el11', name: 'Belkin Surge Protector', price: 1199, unit: '1 pc',  stock: 30,                        category: categoryMap['Electronics'], imageUrl: 'https://picsum.photos/seed/surge-protector/400/400', description: 'Belkin 8-outlet surge protector with 2 USB ports. Safeguards devices from power spikes.' },
    { productKey: 'el12', name: 'Boat USB-C Adapter',     price: 399,  unit: '1 pc',  stock: 100,                       category: categoryMap['Electronics'], imageUrl: 'https://picsum.photos/seed/usb-adapter/400/400', description: 'boAt USB-C to 3.5mm audio adapter. High-res DAC for crystal-clear audio from your phone.' },

    // ── Beauty ──────────────────────────────────────────────────────────────
    { productKey: 'be1',  name: 'Maybelline Foundation',    price: 499,  unit: '30ml',  stock: 60,  badge: 'Popular',     category: categoryMap['Beauty'], imageUrl: 'https://picsum.photos/seed/makeup-foundation/400/400', description: 'Maybelline Fit Me Matte foundation. Poreless finish, lightweight, and available in 18 shades.' },
    { productKey: 'be2',  name: 'MAC Lipstick Ruby Woo',   price: 1750, unit: '1 pc',  stock: 30,  badge: 'Premium',     category: categoryMap['Beauty'], imageUrl: 'https://picsum.photos/seed/red-lipstick/400/400', description: 'MAC Ruby Woo — the iconic matte red lipstick. Bold, long-wearing, and universally flattering.' },
    { productKey: 'be3',  name: 'Himalaya Face Wash',      price: 130,  unit: '150ml', stock: 100, badge: 'Popular',     category: categoryMap['Beauty'], imageUrl: 'https://picsum.photos/seed/face-wash/400/400', description: 'Himalaya Neem Face Wash — purifying gel wash with neem and turmeric for clear, pimple-free skin.' },
    { productKey: 'be4',  name: 'Neutrogena Sunscreen',    price: 599,  unit: '88ml',  stock: 50,  badge: 'Best Seller', category: categoryMap['Beauty'], imageUrl: 'https://picsum.photos/seed/sunscreen-tube/400/400', description: 'Neutrogena Ultra Sheer SPF 50+ sunscreen. Lightweight, non-greasy, and broad-spectrum UVA/UVB protection.' },
    { productKey: 'be5',  name: "L'Oreal Shampoo",         price: 349,  unit: '340ml', stock: 80,                        category: categoryMap['Beauty'], imageUrl: 'https://picsum.photos/seed/shampoo-bottle/400/400', description: "L'Oreal Paris Extraordinary Clay shampoo. Purifies oily roots while nourishing dry ends." },
    { productKey: 'be6',  name: 'Wild Stone Perfume',      price: 399,  unit: '100ml', stock: 70,  badge: 'Popular',     category: categoryMap['Beauty'], imageUrl: 'https://picsum.photos/seed/mens-perfume/400/400', description: 'Wild Stone Ultra Sensual EDP for men. Long-lasting woody fragrance with musky undertones.' },
    { productKey: 'be7',  name: 'Lakme Kajal',             price: 199,  unit: '1 pc',  stock: 90,                        category: categoryMap['Beauty'], imageUrl: 'https://picsum.photos/seed/kajal-eyeliner/400/400', description: 'Lakme Eyeconic Kajal — smudge-proof, waterproof kajal with 22-hour stay. Deep black intensity.' },
    { productKey: 'be8',  name: 'Nivea Body Lotion',       price: 249,  unit: '200ml', stock: 100,                       category: categoryMap['Beauty'], imageUrl: 'https://picsum.photos/seed/body-lotion/400/400', description: 'Nivea Cocoa Nourish Body Lotion — deep moisture with cocoa butter for dry to very dry skin.' },
    { productKey: 'be9',  name: 'Dove Conditioner',        price: 270,  unit: '180ml', stock: 75,                        category: categoryMap['Beauty'], imageUrl: 'https://picsum.photos/seed/hair-conditioner/400/400', description: 'Dove Intense Repair Conditioner — repairs damaged hair and restores smoothness with keratin actives.' },
    { productKey: 'be10', name: 'Biotique Aloe Gel',       price: 160,  unit: '120ml', stock: 85,  badge: 'Natural',     category: categoryMap['Beauty'], imageUrl: 'https://picsum.photos/seed/aloe-vera-gel/400/400', description: 'Biotique Bio Aloe Vera gel — pure, soothing after-sun gel for face and body.' },
    { productKey: 'be11', name: 'Mamaearth Vitamin C Serum',price: 549, unit: '30ml',  stock: 45,  badge: 'Popular',     category: categoryMap['Beauty'], imageUrl: 'https://picsum.photos/seed/vitamin-c-serum/400/400', description: 'Mamaearth Vitamin C Face Serum — brightens skin, fades dark spots, and boosts glow with turmeric.' },
    { productKey: 'be12', name: 'Vaseline Lip Balm',       price: 99,   unit: '1 pc',  stock: 120,                       category: categoryMap['Beauty'], imageUrl: 'https://picsum.photos/seed/lip-balm/400/400', description: 'Vaseline Lip Therapy — moisturising lip balm with petroleum jelly for soft, smooth lips.' },

    // ── Decor ───────────────────────────────────────────────────────────────
    { productKey: 'de1',  name: 'Mandala Wall Art',       price: 599,  unit: '1 pc',   stock: 40,  badge: 'Popular',     category: categoryMap['Decor'], imageUrl: 'https://picsum.photos/seed/wall-art/400/400', description: 'Wooden mandala wall art (12 inches). Hand-carved, paint-ready or natural finish for living rooms.' },
    { productKey: 'de2',  name: 'LED Fairy Lights (10m)', price: 299,  unit: '1 pc',   stock: 100, badge: 'Popular',     category: categoryMap['Decor'], imageUrl: 'https://picsum.photos/seed/fairy-lights/400/400', description: 'Warm white LED fairy lights, 10 metres with 100 LEDs. USB-powered for bedrooms, balconies, or parties.' },
    { productKey: 'de3',  name: 'Money Plant (Pothos)',   price: 199,  unit: '1 pc',   stock: 60,  badge: 'Fresh',       category: categoryMap['Decor'], imageUrl: 'https://picsum.photos/seed/indoor-plant/400/400', description: 'Live money plant in a 4-inch self-watering pot. Low-maintenance, air-purifying indoor plant.' },
    { productKey: 'de4',  name: 'Ceramic Flower Vase',    price: 449,  unit: '1 pc',   stock: 35,                        category: categoryMap['Decor'], imageUrl: 'https://picsum.photos/seed/ceramic-vase/400/400', description: 'Minimalist white ceramic vase (6 inches). Perfect for dried flowers, pampas, or fresh bouquets.' },
    { productKey: 'de5',  name: 'Scented Candle Set',     price: 349,  unit: '3 pcs',  stock: 70,  badge: 'Popular',     category: categoryMap['Decor'], imageUrl: 'https://picsum.photos/seed/scented-candles/400/400', description: 'Soy wax scented candle set — lavender, vanilla, and rose. 25-hour burn time each.' },
    { productKey: 'de6',  name: 'Velvet Cushion Cover',   price: 399,  unit: '2 pcs',  stock: 80,                        category: categoryMap['Decor'], imageUrl: 'https://picsum.photos/seed/velvet-cushion/400/400', description: 'Velvet cushion covers (16x16 inches) in dusty pink. Soft, zip closure, machine washable.' },
    { productKey: 'de7',  name: 'Bedside Table Lamp',     price: 799,  unit: '1 pc',   stock: 30,  badge: 'New',         category: categoryMap['Decor'], imageUrl: 'https://picsum.photos/seed/bedside-lamp/400/400', description: 'Minimalist bedside lamp with a fabric shade and wooden base. Warm E27 bulb included.' },
    { productKey: 'de8',  name: 'Macrame Wall Hanging',   price: 499,  unit: '1 pc',   stock: 45,                        category: categoryMap['Decor'], imageUrl: 'https://picsum.photos/seed/macrame-hanging/400/400', description: 'Handmade cotton macrame wall hanging (24 inches). Bohemian decor for bedrooms and living spaces.' },
    { productKey: 'de9',  name: 'Photo Frame Set',        price: 599,  unit: '5 pcs',  stock: 50,  badge: 'Popular',     category: categoryMap['Decor'], imageUrl: 'https://picsum.photos/seed/photo-frames/400/400', description: 'Gallery wall photo frame set (5 frames in black). Mix of 4x6 and 5x7 sizes.' },
    { productKey: 'de10', name: 'Bamboo Wind Chime',      price: 249,  unit: '1 pc',   stock: 55,                        category: categoryMap['Decor'], imageUrl: 'https://picsum.photos/seed/wind-chime/400/400', description: 'Natural bamboo wind chime with soothing tones. Hand-crafted for balconies and garden spaces.' },
    { productKey: 'de11', name: 'Jute Table Runner',      price: 349,  unit: '1 pc',   stock: 65,                        category: categoryMap['Decor'], imageUrl: 'https://picsum.photos/seed/jute-runner/400/400', description: 'Natural jute table runner (72x12 inches). Rustic farmhouse style for dining tables.' },
    { productKey: 'de12', name: 'Artificial Succulent Set',price: 399,  unit: '4 pcs',  stock: 40,  badge: 'Popular',     category: categoryMap['Decor'], imageUrl: 'https://picsum.photos/seed/artificial-succulent/400/400', description: 'Realistic artificial succulents in mini pots. Zero maintenance, evergreen desk/shelf decor.' },

    // ── Kids ────────────────────────────────────────────────────────────────
    { productKey: 'ki1',  name: 'Building Blocks (100pc)', price: 499,  unit: '1 set',  stock: 50,  badge: 'Popular',     category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/building-blocks/400/400', description: '100-piece interlocking building blocks in vibrant colours. Safe, non-toxic ABS plastic for ages 3+.' },
    { productKey: 'ki2',  name: 'Colouring Kit',           price: 299,  unit: '1 set',  stock: 70,  badge: 'Popular',     category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/coloring-kit/400/400', description: '64-piece colouring kit with crayons, sketch pens, and colour pencils in a carry case.' },
    { productKey: 'ki3',  name: 'Kids Sippy Cup',          price: 199,  unit: '1 pc',   stock: 80,                        category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/sippy-cup/400/400', description: 'Spill-proof sippy cup (300ml) with straw. BPA-free, dishwasher safe, fun animal designs.' },
    { productKey: 'ki4',  name: 'Soft Toy Bear',           price: 399,  unit: '1 pc',   stock: 60,  badge: 'Popular',     category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/teddy-bear/400/400', description: 'Plush teddy bear (12 inches). Super soft, huggable, and machine washable.' },
    { productKey: 'ki5',  name: 'Puzzle Set (4 in 1)',     price: 349,  unit: '1 set',  stock: 55,                        category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/puzzle-set/400/400', description: '4-in-1 jigsaw puzzle set with 15/20/25/30 pieces. Animal themes, perfect for ages 3-6.' },
    { productKey: 'ki6',  name: 'Kids Toothbrush Set',     price: 149,  unit: '2 pcs',  stock: 100,                       category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/kids-toothbrush/400/400', description: 'Soft-bristle toothbrush set for kids with cartoon handles. Dentist recommended for ages 2-6.' },
    { productKey: 'ki7',  name: 'Play-Doh (4 Pack)',       price: 399,  unit: '4 tubs', stock: 45,  badge: 'Popular',     category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/playdoh/400/400', description: 'Play-Doh classic 4-pack in red, blue, yellow, and white. Non-toxic modelling compound.' },
    { productKey: 'ki8',  name: 'Kids Water Bottle',       price: 249,  unit: '1 pc',   stock: 90,                        category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/kids-bottle/400/400', description: 'Insulated kids water bottle (500ml) with flip straw. Leak-proof, BPA-free, unicorn design.' },
    { productKey: 'ki9',  name: 'Storybook Collection',    price: 599,  unit: '5 books',stock: 35,  badge: 'New',         category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/storybook/400/400', description: 'Illustrated storybook set for ages 3-8. Panchatantra tales with colourful pictures.' },
    { productKey: 'ki10', name: 'Baby Cerelac',            price: 299,  unit: '300g',   stock: 70,  badge: 'Popular',     category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/baby-cereal/400/400', description: 'Nestle Cerelac wheat-apple stage 1 baby cereal. Fortified with iron and vitamins for 6+ months.' },
    { productKey: 'ki11', name: 'Kids Sunscreen',          price: 349,  unit: '100ml',  stock: 50,                        category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/kids-sunscreen/400/400', description: 'Mineral kids sunscreen SPF 50. Gentle, tear-free formula safe for sensitive skin.' },
    { productKey: 'ki12', name: 'Toy Car Set',             price: 449,  unit: '6 pcs',  stock: 40,  badge: 'Popular',     category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/toy-cars/400/400', description: 'Die-cast metal toy car set (6 vehicles). Includes police car, fire truck, ambulance, and more.' },
    { productKey: 'ki13', name: 'Baby Feeding Bib Set',    price: 199,  unit: '3 pcs',  stock: 85,                        category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/baby-bibs/400/400', description: 'Waterproof silicone feeding bibs with crumb catcher pocket. Easy clean, adjustable neck.' },
    { productKey: 'ki14', name: 'Musical Rattle Set',      price: 249,  unit: '3 pcs',  stock: 65,  badge: 'New',         category: categoryMap['Kids'], imageUrl: 'https://picsum.photos/seed/baby-rattle/400/400', description: 'BPA-free musical rattle set for infants. Bright colours, soft textures, easy grip for tiny hands.' },
];

const seedDB = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('MongoDB connected');

        await Product.deleteMany({});
        await Category.deleteMany({});
        console.log('Cleared existing data');

        const insertedCategories = await Category.insertMany(categories);
        console.log(`Seeded ${insertedCategories.length} categories`);

        const categoryMap = {};
        insertedCategories.forEach((cat) => { categoryMap[cat.name] = cat._id; });

        const products = getProducts(categoryMap);
        const insertedProducts = await Product.insertMany(products);
        console.log(`Seeded ${insertedProducts.length} products`);

        // Print the PRODUCT_ID_MAP for frontend
        console.log('\n=== PRODUCT_ID_MAP (copy into your frontend) ===');
        console.log('const PRODUCT_ID_MAP = {');
        insertedProducts.forEach((p) => {
            console.log(`    '${p.productKey}': '${p._id}',`);
        });
        console.log('};');

        await mongoose.disconnect();
        console.log('\nDone!');
    } catch (err) {
        console.error('Seed error:', err.message);
        process.exit(1);
    }
};

seedDB();